-- Total sales
SELECT SUM(TOTAL_AMOUNT) AS TOTAL_SALES
FROM SALESTABLE;

-- Sales by region
SELECT REGION_NAME, SUM(TOTAL_AMOUNT) AS TOTAL_SALES
FROM SALESTABLE
JOIN REGIONSTABLE ON SALEStable.REGION_ID = REGIONStable.REGION_ID
GROUP BY REGION_NAME
ORDER BY TOTAL_SALES DESC;

-- Monthly sales trends
SELECT EXTRACT(YEAR FROM SALE_DATE) AS YEAR, EXTRACT(MONTH FROM SALE_DATE) AS MONTH, SUM(TOTAL_AMOUNT) AS TOTAL_SALES
FROM SALESTABLE
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH;
