use SALESPERFORMANCEDB;
create table salestable(SALE_ID INT PRIMARY KEY,
    PRODUCT_ID INT,
    REGION_ID INT,
    SALE_DATE DATE,
    QUANTITY INT,
    TOTAL_AMOUNT DECIMAL(10, 2) ,
    FOREIGN KEY (PRODUCT_ID) REFERENCES (PRODUCT_ID),
    FOREIGN KEY (REGION_ID) REFERENCES (REGION_ID) 
    );




use salesperformancedb;
CREATE TABLE PRODUCTSTABLE (
    PRODUCT_ID INT PRIMARY KEY,
    PRODUCT_NAME STRING,
    CATEGORY STRING,
    PRICE DECIMAL(10, 2)
);





USE SALESPERFORMANCEDB;
CREATE TABLE REGIONSTABLE (
    REGION_ID INT PRIMARY KEY,
    REGION_NAME STRING
);
